pull_request_rules:
  - name: controlled queue test
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=controlled-ci
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    merge_method: squash
    queue_conditions:
      - check-success=controlled-ci
